name: technical_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  badges: 2.0.2
  get: 4.6.5
  sizer: 2.0.15
  intl: 0.17.0
  dio: 4.0.6
  google_fonts: 2.2.0
  remixicon: 1.0.0
  hive: 2.1.0
  hive_flutter: 1.1.0
  xml: 5.3.1
  cached_network_image: 3.2.0
  carousel_slider: 4.0.0
  connectivity_plus: 2.3.3
  shimmer: 2.0.0
  flutter_html: 2.2.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  hive_generator: ^1.1.2
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

